---
title: "evalwaterfallr"
author: "JC"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
references:
- id: kasmanetaliepec2015
  title: Development of Order-Independent Waterfall Graphics to Enable Comprehensive Understanding of Impact Evaluation Results
  author:
  - family: Kasman
    given: Robert
  - family: Scheer
    given: Adam  
  - family: Sackman
    given: Rachel
  - family: Friedmann
    given: Rafael
  - family: Berman
    given: Janice
  container-title: Proceedings of the 2015 International Energy Program Evaluation Conference
  volume: Long Beach, California
  issued:
    year: 2015
    month: 8      
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
  
  
---

```{r setup, include=FALSE, echo=FALSE, message=FALSE, warning=FALSE}
options(scipen=999) # avoid scientific notation
library(knitr)
knitr::opts_knit$set(upload.fun = image_uri) #embed the images
knitr::opts_chunk$set(collapse = T, comment = "#>")

printTable <- function(x) {
    library(xtable)
    print(xtable::xtable(x), type ="HTML", include.rownames=FALSE, comment = FALSE)
}
```

This document describes how to create order independent permutations and waterfall graphics using evalwaterfallr. There are three functions in the package. Two of them are intended to be used directly: `waterfallPrep()` and `waterfallPlot()`. The `wParamPermute()` function is called by `waterfallPrep()` and could be used on its own by some users, but it is not expected. 

## Motivation
Evaluated savings (_ex post_) are often shown as either Gross or Net values and compared directly with the Gross or Net reported savings (_ex ante_). The difference in the values depends upon parameters which can be defined as ratios or multiplicative factors. 

## waterfallPrep()
This function takes the input of multiplicative parameters (up to 10) and the key values of Gross Reported, NTG Reported and NTG Evaluated. All permutations of the order of multiplicative adjustments are determined. The way that @kasmanetaliepec2015 presents the approach is:

1. Perform all possible permutations of the sequential application of multiplicative impact parameter adjustments.
2. Sum the changes due to each individual impact parameter.
3. Divide the results of Step 2 by the total number of permutations.
4. Permute the GRR and $NTG_{RR}$ adjustments.
5. Re-calculate the impact parameter adjustments maintaining their relative ratios from step 3 such that summing the impact parameter adjustments equals $grr_{N}$.

These maths are straightforward, but are error prone and time consuming in spreadsheet applications. The time and risk increases with the number of parameters. A three parameter equation, like lighting, requires six permutations, but a four parameter equation requires 24. 



## waterfallPlot()
## wParamPermute()
